spring:
  application:
    name: NETWORK_OTUS
#  liquibase:
#    enabled: true
#    change-log: classpath:/db.changelog-master.yaml
#springdoc:
#  swagger-ui:
#    path: /swagger-ui/index.html
#  api-docs:
#    path: /api-docs
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
logging:
  level:
    com:
      otus:
        network:
          repository: debug
otus:
  db:
    db: ${POSTGRES_DB:otus}
    user: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    host: ${POSTGRES_HOST:localhost}
    port: ${POSTGRES_PORT:5432}